version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
  unity: game-ci/unity@1.4.0

jobs:
  export-ios:
    executor:
      name: unity/ubuntu
      editor_version: 2021.3.2f1
      resource_class: xlarge
      target_platform: ios
    steps:
      - checkout
      - unity/prepare-env
      - unity/build:
          build-target: iOS
          compress: false
          store-artifacts: false
          project-path: "src"
      - persist_to_workspace:
          root: .
          paths:
            - src/Builds/iOS
      - run:
          command: pwd
      - run:
          command: ls -laR
      - run:
          command: ls -laR ~/

  build-and-beta-ios:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1
    working_directory:
      ./src/Builds/iOS/iOS
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: pwd
      - run:
          command: ls -laR
      - run:
          command: ls -laR ~/
      - run:
          command: ls -laR ./src/Builds/iOS
      - run:
          command: xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone archive -archivePath Unity2D-Demo-Game-CI-CD.xarchive PROVISIONING_PROFILE=4a3abac3-8987-4c0a-b99c-1db774de2743
      - run:
          command: xcodebuild -exportArchive -archivePath Unity2D-Demo-Game-CI-CD.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist PROVISIONING_PROFILE=4a3abac3-8987-4c0a-b99c-1db774de2743
      - run:
          command: ls -laR
      - run:
          command: ls -laR ./src/Builds/iOS
      - store_artifacts:
          path: output

workflows:
  build-unity-project:
    jobs:
      - export-ios:
          context: UnityTesuto
      - build-and-beta-ios:
          requires:
            - export-ios
          context:
            - mobile
