version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
  unity: game-ci/unity@1.4.0

jobs:
  export-ios:
    executor:
      name: unity/ubuntu
      editor_version: 2021.3.2f1
      resource_class: xlarge
      target_platform: ios
    steps:
      - checkout
      - unity/prepare-env
      - unity/build:
          build-target: iOS
          compress: false
          store-artifacts: false
          project-path: "src"
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  build-and-beta-ios:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - ruby/install-deps:
          key: ios
      - run: bundle exec fastlane ios beta


workflows:
  build-unity-project:
    jobs:
      - export-ios:
          context: UnityTesuto
      - build-and-beta-ios:
          requires:
            - export-ios
          context:
            - mobile
