version: 2.1

# set unity as 1.4.0
orbs:
  unity: game-ci/unity@1.4.0

# set context as UnityTesuto (I set it in OrganizationSettings->Contexts)
# set unity-serial-var-name instead of unity-license-var-name
workflows:
  build-unity-project:
    jobs:
      - unity/build:
          name: "build-ios"
          step-name: "Build iOS"
          unity-serial-var-name: "UNITY_SERIAL"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "ios"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "src"
          build-target: "iOS"
          context: UnityTesuto