version: 2.1

# set unity as 1.4.0
orbs:
  unity: game-ci/unity@1.4.0

# set context as UnityTesuto (I set it in OrganizationSettings->Contexts)
# set unity-serial-var-name instead of unity-license-var-name
workflows:
  build-unity-project:
    jobs:
      - unity/test:
          name: "test-linux"
          step-name: "Check if the tests run and results are uploaded"
          unity-serial-var-name: "UNITY_SERIAL"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.9f1"
            resource_class: "medium"
          project-path: "src"
          test-platform: "playmode"
          context: UnityTesuto
      - unity/build:
          name: "build-webgl"
          step-name: "Build WebGL"
          unity-serial-var-name: "UNITY_SERIAL"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "webgl"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: "WebGL"
          compress: false
          context: UnityTesuto
